project:
  type: website
  render:
    - "*.qmd"
    - "!slides/R/"

website:
  title: "R Best Practices"
  description: |
    "Description and slides for an introductory course on best practices in R"
  repo-url: https://github.com/hpcleuven/R-best-practices
  repo-actions: source
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides

format:
  html:
    theme:
      - slate
      - vsc.scss
    toc: true



